project:
  type: book
  output-dir: docs

book:
  title: "CABANANet: Train the Trainers"
  author: "Evelia Coss, Miguel Maga帽a y Domingo Martinez"
  date: "04/29/2025"
  page-navigation: true
  chapters:
  - index.qmd
  - part: "**Secci贸n 1** - Bienvenida e Introducci贸n"
    chapters:
    - intro.qmd
    - Cap1.qmd
  - part: "**Secci贸n 2** - Modelos mentales y carga Cognitiva"
    chapters:
    - Cap2A.qmd
    - Cap2B.qmd
  - part: "**Secci贸n 3** - Memoria y otros principios"
    chapters:
    - Cap3A.qmd
    - Cap3B.qmd
    - Cap3C.qmd
  - part: "**Secci贸n 4** - Audiencia y Simulaci贸n de entrenamiento"
    chapters:
    - Cap4A.qmd
    - Cap4B.qmd
    - Cap4C.qmd
  - part: "**Secci贸n 5** - Ense帽ar en l铆nea y Planificaci贸n de cursos"
    chapters:
    - Cap5A.qmd
    - Cap5B.qmd
  - part: "**Secci贸n 6** - Programaci贸n en vivo y entrenamientos"
    chapters:
    - Cap6A.qmd
    - Cap6B.qmd
    - Cap6C.qmd
    - Cap6D.qmd
    - Cap6E.qmd    
  # Information
  site-url: https://cabana.network/ # URL del sitio completo CABANANet
  repo-url: https://github.com/EveliaCoss/CABANAnet_TrainTrainers2025 # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "figures/cabananet_logo.png" # icono de la pagina en pestana

format:
  html:
    logo: "figures/cabananet_logo.png"
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual

